" Colours suitable for a dark background, which is what my Linux console,
" xterms and rxvts are configured to have.

set shell=/bin/sh

set nocompatible
filetype off

packadd! dracula

filetype plugin indent on

" Airline configuration
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

set nocp

" 256 colors!
set t_Co=256

" Indenting 
set ai
set cin

set grepprg=ack
set grepformat=%f:%l:%m

" Tabs at 2 spaces.
set tabstop=2
set smarttab
set shiftwidth=2
" And make them spaces, instrad of real tabs.
set autoindent
set expandtab
set backspace=start,indent

" C++ indenting: one space for public, private, etc., one more space for
" inside that.
set cinoptions+=g1,h1

" Shows matching parens
set sm

" Set the title of the term when editing
set title

" Display tabs weird and trailing space so that I NOTICE the
" evil things.
set list listchars=tab:»·,trail:‽

set textwidth=0

" Python is notorious for long lines, and not wanting to wrap them.
autocmd FileType python set textwidth=0

" Tex Settings 
autocmd FileType tex set noai
autocmd FileType tex set nocin
autocmd Filetype tex filetype plugin indent off

execute "set t_8f=\e[38;2;%lu;%lu;%lum"
execute "set t_8b=\e[48;2;%lu;%lu;%lum"

set termguicolors

" Colors!
syntax enable
" set background=dark
colorscheme dracula

set cursorline
" Except, I want transparent backgrounds
hi Normal ctermbg=None
hi LineNr ctermbg=None
" Except, on the current line.
hi CursorLineNr cterm=bold ctermfg=33 ctermbg=233 guifg=#0087ff guibg=#333333
hi CursorLine ctermbg=233 guibg=#333333

" Searching hilite and auto-jump
set incsearch
set hlsearch

" Ignore case when searching, unless we have at least one uppercase character
set ignorecase
set smartcase

" Tabs actually mean something in makefiles
autocmd FileType make     set noexpandtab

map <leader>h :noh<CR>

" CTAGS!
map <silent> <F5> :!ctags -R --exclude=.svn --exclude=.git --exclude=log *<CR>

" Folds! Rarely useful!
set nofoldenable
set foldlevel=100
let g:vim_markdown_folding_disabled=1  " Yes, even in markdown

" Show the status line all the time
set laststatus=2
set encoding=utf-8

" Hilight lines that go over 80 characters.
" highlight OverLength ctermbg=darkred ctermfg=white guibg=#592929
" match OverLength /\%81v.\+/

"command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
"  \ | wincmd p | diffthis

" Better split stuff
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

" Numbers in relation to the cursor
set relativenumber
set number

" I am slow with the shift key release ALL THE TIME
command W w
command Q q
command Wq wq

