#!/usr/bin/env bash

xset fp+ ${HOME}/.fonts
xset fp rehash

setxkbmap -option ctrl:nocaps

pasystray &
nm-tray &

if [ -x "${HOME}/.xsession.local" ]; then
  source ${HOME}/.xsession.local
fi

if [ -x "${HOME}/backgrounds/set.sh" ]; then
  ${HOME}/backgrounds/set.sh
fi

xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

ssh-agent i3
