
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt correctall

# General aliases
alias apt="sudo apt"
alias ccal="nocorrect ccal"

# Debian Stuff
export DEBEMAIL="Marie Janssen <jamuraa@debian.org>"

export EDITOR="vim"
export VISUAL="vim"

path+=$HOME/local/bin

# UTF-8 please.
# export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# In Stunning 256 colors (where available)
if [ -e /usr/share/terminfo/r/rxvt-256color ]; then
  export TERM='rxvt-256color'
else
  export TERM='xterm-color'
fi

alias durn="du --max-depth=1 -k | sort -rn"

export PATH

if [ -e $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

